version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: postgres-nwl-setup
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - nwl-setup:/var/lib/postgres/data
    ports:
      - 5432:5432

volumes:
  nwl-setup: